export enum CreditApplicationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  CONDITIONAL_APPROVAL = 'CONDITIONAL_APPROVAL',
  DENIED = 'DENIED',
  EXPIRED = 'EXPIRED',
}

export enum CreditLimitStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  EXCEEDED = 'EXCEEDED',
}

export enum CreditHoldReason {
  PAYMENT_OVERDUE = 'PAYMENT_OVERDUE',
  CREDIT_LIMIT_EXCEEDED = 'CREDIT_LIMIT_EXCEEDED',
  FRAUD_SUSPECTED = 'FRAUD_SUSPECTED',
  INSUFFICIENT_INSURANCE = 'INSUFFICIENT_INSURANCE',
  CARRIER_OOS = 'CARRIER_OOS',
  MANUAL_HOLD = 'MANUAL_HOLD',
}

export enum CollectionActivityType {
  CALL = 'CALL',
  EMAIL = 'EMAIL',
  LETTER = 'LETTER',
  LEGAL_NOTICE = 'LEGAL_NOTICE',
  COLLECTIONS_AGENCY = 'COLLECTIONS_AGENCY',
}

export enum PaymentPlanStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DEFAULTED = 'DEFAULTED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentTerms {
  NET_15 = 'NET_15',
  NET_21 = 'NET_21',
  NET_30 = 'NET_30',
  NET_45 = 'NET_45',
  COD = 'COD',
}

export enum PaymentFrequency {
  WEEKLY = 'WEEKLY',
  BI_WEEKLY = 'BI_WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
}
