export const ROLES = {
  // System roles
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',

  // Sales roles
  SALES_REP: 'SALES_REP',
  SALES_MANAGER: 'SALES_MANAGER',
  PRICING_ANALYST: 'PRICING_ANALYST',

  // Operations roles
  DISPATCHER: 'DISPATCHER',
  OPERATIONS: 'OPERATIONS',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',

  // Carrier roles
  CARRIER_MANAGER: 'CARRIER_MANAGER',
  SAFETY_MANAGER: 'SAFETY_MANAGER',

  // Claims roles
  CLAIMS_MANAGER: 'CLAIMS_MANAGER',
  CLAIMS_ADJUSTER: 'CLAIMS_ADJUSTER',
  CLAIMS_VIEWER: 'CLAIMS_VIEWER',

  // EDI roles
  EDI_MANAGER: 'EDI_MANAGER',

  // Factoring roles
  FACTORING_MANAGER: 'FACTORING_MANAGER',
  COLLECTIONS_AGENT: 'COLLECTIONS_AGENT',
  BILLING: 'BILLING',

  // Legal
  LEGAL: 'LEGAL',

  // Finance roles
  ACCOUNTING: 'ACCOUNTING',
  ACCOUNTING_MANAGER: 'ACCOUNTING_MANAGER',

  // Support roles
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  SUPPORT_AGENT: 'SUPPORT_AGENT',

  // External roles (portal users)
  CUSTOMER: 'CUSTOMER',
  CARRIER: 'CARRIER',
  AGENT: 'AGENT',

  // Marketing
  MARKETING: 'MARKETING',

  // Specialized
  COMPLIANCE: 'COMPLIANCE',
  CLAIMS_HANDLER: 'CLAIMS_HANDLER',
  CONTRACT_MANAGER: 'CONTRACT_MANAGER',
  CONTRACTS_MANAGER: 'CONTRACTS_MANAGER',
  CONTRACTS_VIEWER: 'CONTRACTS_VIEWER',
  AGENT_MANAGER: 'AGENT_MANAGER',
  EXECUTIVE: 'EXECUTIVE',
  SYSTEM_INTEGRATOR: 'SYSTEM_INTEGRATOR',

  // Credit roles
  CREDIT_ANALYST: 'CREDIT_ANALYST',
  CREDIT_VIEWER: 'CREDIT_VIEWER',

  // Legacy generic roles (temporary)
  VIEWER: 'VIEWER',
  USER: 'USER',
  MANAGER: 'MANAGER',
  READ_ONLY: 'READ_ONLY',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];
