/**
 * Complete Truck/Trailer Database with Accurate Specifications
 *
 * Comprehensive list of all trailer types used in Continental USA
 *
 * CRITICAL: Deck heights are essential for calculating total load height
 * Total Height = Cargo Height + Deck Height (must be <= 13.5 ft legal limit)
 */

import type { TruckType } from './types'

// Re-export legal limits from types for convenience
export { LEGAL_LIMITS, SUPERLOAD_THRESHOLDS } from './types'

export const trucks: TruckType[] = [
  // ===========================
  // FLATBED TRAILERS
  // ===========================
  {
    id: 'flatbed-48',
    name: "Flatbed 48'",
    category: 'FLATBED',
    description: 'Standard 48-foot flatbed trailer. Most common and economical choice for freight that fits within legal dimensions.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 48000,
    tareWeight: 15000,
    maxLegalCargoHeight: 8.5, // 13.5 - 5.0
    maxLegalCargoWidth: 8.5,
    features: [
      'Most economical option',
      'Widely available',
      'Easy loading from sides',
      'Standard tie-down points every 2 feet',
      'Can add tarps for weather protection',
    ],
    bestFor: [
      'Steel coils and beams',
      'Lumber and building materials',
      "Machinery under 8.5' tall",
      'Palletized freight',
      'Construction materials',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'flatbed-53',
    name: "Flatbed 53'",
    category: 'FLATBED',
    description: 'Extended 53-foot flatbed for longer cargo. Maximum legal trailer length for standard operations.',
    deckHeight: 5.0,
    deckLength: 53,
    deckWidth: 8.5,
    maxCargoWeight: 45000,
    tareWeight: 16000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      '5 extra feet of deck space',
      'Good for longer loads',
      "Same height as 48' flatbed",
      'Standard tie-down points',
    ],
    bestFor: [
      'Long steel beams',
      'Extended machinery',
      'Multiple items requiring extra length',
      'Pipe and tubing',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'stretch-flatbed',
    name: 'Stretch Flatbed',
    category: 'FLATBED',
    description: "Extendable flatbed that can stretch from 48' to 80' or more for extra-long loads. Requires oversize permits when extended.",
    deckHeight: 5.0,
    deckLength: 80, // Extended length
    deckWidth: 8.5,
    maxCargoWeight: 43000,
    tareWeight: 18000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      "Extends from 48' to 80'+",
      'For extra-long cargo',
      'Telescoping design',
      'Requires oversize permits when stretched',
    ],
    bestFor: [
      'Wind turbine blades',
      'Long structural steel',
      'Bridge beams',
      'Utility poles',
      'Long pipe strings',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'hotshot-40',
    name: "Hotshot 40'",
    category: 'FLATBED',
    description: 'Gooseneck flatbed pulled by heavy-duty pickup (Class 3-5). Faster, more economical for lighter loads.',
    deckHeight: 3.5,
    deckLength: 40,
    deckWidth: 8.5,
    maxCargoWeight: 16500,
    tareWeight: 7000,
    maxLegalCargoHeight: 10.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Quick dispatch',
      'Lower cost than full-size',
      'Fits in tighter spaces',
      'Lower deck than standard flatbed',
    ],
    bestFor: [
      'LTL (Less Than Truckload)',
      'Time-critical small loads',
      'Farm equipment',
      'Small construction equipment',
      'Vehicles',
    ],
    powerUnitWeight: 9000,
    loadingMethod: 'drive-on',
  },

  // ===========================
  // STEP DECK TRAILERS
  // ===========================
  {
    id: 'step-deck-48',
    name: "Step Deck 48'",
    category: 'STEP_DECK',
    description: "Standard step deck with upper deck (11') and lower main deck (37'). Lower deck height allows taller cargo.",
    deckHeight: 3.5,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 37,
    deckZones: [
      { name: 'upper', startX: 0, endX: 11, deckHeight: 5.0, maxCargoHeight: 8.5 },
      { name: 'lower', startX: 11, endX: 48, deckHeight: 3.5, maxCargoHeight: 10.0 },
    ],
    maxCargoWeight: 48000,
    tareWeight: 16000,
    maxLegalCargoHeight: 10.0, // 13.5 - 3.5 (lower deck)
    maxLegalCargoWidth: 8.5,
    features: [
      "Lower deck height (3.5' vs 5')",
      'Drive-on capability with ramps',
      'Upper deck for smaller items',
      'Good balance of height and capacity',
    ],
    bestFor: [
      'Forklifts and small equipment',
      "Cargo 8.5' to 10' tall",
      'Vehicles that can drive on',
      'Agricultural equipment',
      'Scissor lifts and aerial lifts',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'step-deck-53',
    name: "Step Deck 53'",
    category: 'STEP_DECK',
    description: "Extended 53-foot step deck with more deck space. Upper deck (11') and lower main deck (42').",
    deckHeight: 3.5,
    deckLength: 53,
    deckWidth: 8.5,
    wellLength: 42,
    deckZones: [
      { name: 'upper', startX: 0, endX: 11, deckHeight: 5.0, maxCargoHeight: 8.5 },
      { name: 'lower', startX: 11, endX: 53, deckHeight: 3.5, maxCargoHeight: 10.0 },
    ],
    maxCargoWeight: 46000,
    tareWeight: 17000,
    maxLegalCargoHeight: 10.0, // 13.5 - 3.5 (lower deck)
    maxLegalCargoWidth: 8.5,
    features: [
      "53' overall length",
      'Longer lower deck section',
      'Drive-on capability',
      'More versatile for longer equipment',
    ],
    bestFor: [
      "Longer equipment up to 10' tall",
      'Multiple pieces of machinery',
      'Extended agricultural equipment',
      'Construction vehicles',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'low-pro-step-deck',
    name: 'Low Pro Step Deck',
    category: 'STEP_DECK',
    description: 'Low profile step deck with reduced deck height for taller cargo. Uses low-profile tires.',
    deckHeight: 2.5,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 37,
    deckZones: [
      { name: 'upper', startX: 0, endX: 11, deckHeight: 4.0, maxCargoHeight: 9.5 },
      { name: 'lower', startX: 11, endX: 48, deckHeight: 2.5, maxCargoHeight: 11.0 },
    ],
    maxCargoWeight: 44000,
    tareWeight: 17000,
    maxLegalCargoHeight: 11.0, // 13.5 - 2.5 (lower deck)
    maxLegalCargoWidth: 8.5,
    features: [
      "Extra-low deck (2.5')",
      'Uses low-profile tires',
      'Maximum legal cargo height',
      'Drive-on with ramps',
    ],
    bestFor: [
      "Cargo 10' to 11' tall",
      'Tall equipment that fits legally',
      'Borderline oversize loads',
      'Maximizing legal height',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'stretch-step-deck',
    name: 'Stretch Step Deck',
    category: 'STEP_DECK',
    description: "Extendable step deck for tall and long cargo. Can stretch from 48' to 65'+ as needed.",
    deckHeight: 3.5,
    deckLength: 65,
    deckWidth: 8.5,
    wellLength: 50,
    deckZones: [
      { name: 'upper', startX: 0, endX: 11, deckHeight: 5.0, maxCargoHeight: 8.5 },
      { name: 'lower', startX: 11, endX: 65, deckHeight: 3.5, maxCargoHeight: 10.0 },
    ],
    maxCargoWeight: 43000,
    tareWeight: 19000,
    maxLegalCargoHeight: 10.0, // 13.5 - 3.5 (lower deck)
    maxLegalCargoWidth: 8.5,
    features: [
      'Extendable deck',
      'For tall + long cargo',
      'Lower deck than flatbed',
      'Versatile for oversized loads',
    ],
    bestFor: [
      'Long and tall equipment',
      'Extended agricultural machines',
      'Crane booms',
      'Long industrial equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },

  // ===========================
  // RGN (REMOVABLE GOOSENECK)
  // ===========================
  {
    id: 'rgn-2axle',
    name: 'RGN 2-Axle',
    category: 'RGN',
    description: 'Standard 2-axle removable gooseneck with very low deck. Gooseneck detaches for front-loading.',
    deckHeight: 2.0,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 29,
    wellHeight: 2.0,
    deckZones: [
      { name: 'gooseneck', startX: 0, endX: 8, deckHeight: 4.0, maxCargoHeight: 9.5 },
      { name: 'well', startX: 8, endX: 40, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 40, endX: 48, deckHeight: 3.0, maxCargoHeight: 10.5 },
    ],
    maxCargoWeight: 42000,
    tareWeight: 20000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      "Very low deck height (2')",
      'Detachable gooseneck for drive-on loading',
      'Ideal for tracked equipment',
      'Can handle tall machinery',
      'Hydraulic detach system',
    ],
    bestFor: [
      'Excavators and dozers',
      'Tracked equipment',
      "Tall machinery (10'-11.5')",
      'Equipment that must drive on',
      'Cranes and heavy construction equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'rgn-3axle',
    name: 'RGN 3-Axle',
    category: 'RGN',
    description: 'Heavy-duty 3-axle RGN for heavier loads. Same low deck height with increased weight capacity.',
    deckHeight: 2.0,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 29,
    wellHeight: 2.0,
    deckZones: [
      { name: 'gooseneck', startX: 0, endX: 8, deckHeight: 4.0, maxCargoHeight: 9.5 },
      { name: 'well', startX: 8, endX: 40, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 40, endX: 48, deckHeight: 3.0, maxCargoHeight: 10.5 },
    ],
    maxCargoWeight: 52000,
    tareWeight: 22000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      'Extra axle for heavier loads',
      'Same low deck as standard RGN',
      'Better weight distribution',
      'Higher capacity for heavy equipment',
    ],
    bestFor: [
      'Heavy excavators (CAT 330+)',
      'Large dozers',
      'Mining equipment',
      'Heavy tracked machinery',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'rgn-4axle',
    name: 'RGN 4-Axle',
    category: 'RGN',
    description: 'Extra heavy-duty 4-axle RGN for the heaviest tracked equipment. Maximum weight distribution.',
    deckHeight: 2.0,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 29,
    wellHeight: 2.0,
    deckZones: [
      { name: 'gooseneck', startX: 0, endX: 8, deckHeight: 4.0, maxCargoHeight: 9.5 },
      { name: 'well', startX: 8, endX: 40, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 40, endX: 48, deckHeight: 3.0, maxCargoHeight: 10.5 },
    ],
    maxCargoWeight: 65000,
    tareWeight: 26000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      '4 axles for maximum weight',
      'Heaviest legal capacity',
      'Excellent weight distribution',
      'Low deck for tall equipment',
    ],
    bestFor: [
      'Heaviest excavators (CAT 390+)',
      'Mining haul trucks',
      'Large cranes',
      'Extreme heavy equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'stretch-rgn',
    name: 'Stretch RGN',
    category: 'RGN',
    description: "Extendable RGN for long and tall heavy equipment. Stretches from 48' to 65'+ for oversized loads.",
    deckHeight: 2.0,
    deckLength: 65,
    deckWidth: 8.5,
    wellLength: 45,
    wellHeight: 2.0,
    deckZones: [
      { name: 'gooseneck', startX: 0, endX: 8, deckHeight: 4.0, maxCargoHeight: 9.5 },
      { name: 'well', startX: 8, endX: 53, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 53, endX: 65, deckHeight: 3.0, maxCargoHeight: 10.5 },
    ],
    maxCargoWeight: 48000,
    tareWeight: 24000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      'Extendable deck length',
      'Low deck height maintained',
      'Drive-on capability',
      'For long, tall, heavy equipment',
    ],
    bestFor: [
      'Long-reach excavators',
      'Crane booms on equipment',
      'Mining equipment with attachments',
      'Extended drilling equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },

  // ===========================
  // LOWBOY TRAILERS
  // ===========================
  {
    id: 'lowboy-2axle',
    name: 'Lowboy 2-Axle',
    category: 'LOWBOY',
    description: "Standard lowboy with lowest deck height available (1.5'). Fixed gooseneck, requires crane loading.",
    deckHeight: 1.5,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 24,
    wellHeight: 1.5,
    maxCargoWeight: 40000,
    tareWeight: 20000,
    maxLegalCargoHeight: 12.0, // 13.5 - 1.5
    maxLegalCargoWidth: 8.5,
    features: [
      "Lowest deck height available (1.5')",
      'Maximum cargo height clearance',
      'Very stable for tall loads',
      'Fixed gooseneck (stronger)',
    ],
    bestFor: [
      "Tallest equipment (11.5'-12')",
      'Large transformers',
      'Oversized industrial equipment',
      'Crane components',
      'Wind turbine parts',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'lowboy-3axle',
    name: 'Lowboy 3-Axle',
    category: 'LOWBOY',
    description: 'Heavy-duty lowboy with 3 axles for heavier tall loads. Maximum capacity for standard lowboy.',
    deckHeight: 1.5,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 24,
    wellHeight: 1.5,
    maxCargoWeight: 55000,
    tareWeight: 25000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Maximum weight capacity',
      'Lowest deck for tallest cargo',
      '3 axles for weight distribution',
      'Most versatile for oversize loads',
    ],
    bestFor: [
      'Heaviest tall equipment',
      'Large transformers',
      'Mining equipment',
      'Superload candidates',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'lowboy-4axle',
    name: 'Lowboy 4-Axle',
    category: 'LOWBOY',
    description: 'Extra heavy-duty 4-axle lowboy for the heaviest tall loads. Used for superloads.',
    deckHeight: 1.5,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 24,
    wellHeight: 1.5,
    maxCargoWeight: 70000,
    tareWeight: 30000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 8.5,
    features: [
      '4 axles for extreme weight',
      'Superload capable',
      'Best weight distribution',
      'Lowest deck available',
    ],
    bestFor: [
      'Power transformers',
      'Nuclear components',
      'Heavy industrial equipment',
      'Bridge sections',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'detach-lowboy',
    name: 'Detachable Lowboy',
    category: 'LOWBOY',
    description: 'Lowboy with detachable gooseneck for drive-on loading. Combines low deck with loading flexibility.',
    deckHeight: 1.8,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 26,
    wellHeight: 1.8,
    maxCargoWeight: 45000,
    tareWeight: 22000,
    maxLegalCargoHeight: 11.7,
    maxLegalCargoWidth: 8.5,
    features: [
      'Detachable gooseneck',
      'Drive-on loading option',
      'Nearly as low as fixed lowboy',
      'More versatile than fixed',
    ],
    bestFor: [
      'Tall tracked equipment',
      'Equipment that can drive on',
      'When crane not available',
      'Versatile heavy loads',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'stretch-lowboy',
    name: 'Stretch Lowboy',
    category: 'LOWBOY',
    description: 'Extendable lowboy for long and very tall cargo. Can extend deck length significantly.',
    deckHeight: 1.5,
    deckLength: 65,
    deckWidth: 8.5,
    wellLength: 40,
    wellHeight: 1.5,
    maxCargoWeight: 50000,
    tareWeight: 28000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Extendable deck',
      'Lowest deck height',
      'For long + very tall cargo',
      'Maximum height clearance',
    ],
    bestFor: [
      'Long transformers',
      'Extended tall equipment',
      'Reactor vessels',
      'Long industrial tanks',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },

  // ===========================
  // DOUBLE DROP TRAILERS
  // ===========================
  {
    id: 'double-drop',
    name: 'Double Drop',
    category: 'DOUBLE_DROP',
    description: 'Three-level trailer with low center well. Combines height advantage with length for tall, long cargo.',
    deckHeight: 2.0,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 25,
    wellHeight: 2.0,
    deckZones: [
      { name: 'front', startX: 0, endX: 11.5, deckHeight: 4.5, maxCargoHeight: 9.0 },
      { name: 'well', startX: 11.5, endX: 36.5, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 36.5, endX: 48, deckHeight: 4.5, maxCargoHeight: 9.0 },
    ],
    maxCargoWeight: 45000,
    tareWeight: 18000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      'Low center well section',
      'Front and rear decks for smaller items',
      'Good for tall + long machinery',
      'Versatile loading options',
    ],
    bestFor: [
      'Tall machinery with length',
      'Industrial generators',
      'Large compressors',
      'Processing equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'stretch-double-drop',
    name: 'Stretch Double Drop',
    category: 'DOUBLE_DROP',
    description: 'Extendable double drop for extra-long tall cargo. Well section can extend significantly.',
    deckHeight: 2.0,
    deckLength: 65,
    deckWidth: 8.5,
    wellLength: 40,
    wellHeight: 2.0,
    deckZones: [
      { name: 'front', startX: 0, endX: 12.5, deckHeight: 4.5, maxCargoHeight: 9.0 },
      { name: 'well', startX: 12.5, endX: 52.5, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 52.5, endX: 65, deckHeight: 4.5, maxCargoHeight: 9.0 },
    ],
    maxCargoWeight: 42000,
    tareWeight: 21000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      'Extendable well section',
      'Low center deck',
      'For extra-long tall cargo',
      'Multiple deck levels',
    ],
    bestFor: [
      'Long industrial equipment',
      'Extended tanks and vessels',
      'Large generator packages',
      'Mining equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },

  // ===========================
  // SPECIALIZED TRAILERS
  // ===========================
  {
    id: 'landoll',
    name: 'Landoll (Tilt Bed)',
    category: 'LANDOLL',
    description: 'Self-loading tilt bed trailer. Tilts and slides for ground-level loading without ramps or cranes.',
    deckHeight: 2.5,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 50000,
    tareWeight: 18000,
    maxLegalCargoHeight: 11.0, // 13.5 - 2.5
    maxLegalCargoWidth: 8.5,
    features: [
      'Self-loading capability',
      'Tilts to ground level',
      'No external equipment needed',
      'Fast loading/unloading',
      'Hydraulic tilt and slide',
    ],
    bestFor: [
      'Containers',
      'Equipment without crane access',
      'Remote locations',
      'Quick turnaround loads',
      'Vehicles and small equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'tilt',
  },
  {
    id: 'conestoga',
    name: 'Conestoga',
    category: 'CONESTOGA',
    description: 'Flatbed with retractable tarp system. Provides weather protection while maintaining flatbed flexibility.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 44000,
    tareWeight: 17000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Built-in tarp system',
      'Weather protection',
      'Side loading capability',
      'Quick tarp deployment',
      'No manual tarping required',
    ],
    bestFor: [
      'Weather-sensitive cargo',
      'Paper products',
      'Food-grade freight',
      'Finished goods needing protection',
      'Electronics and machinery',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },
  {
    id: 'dry-van-53',
    name: "Dry Van 53'",
    category: 'DRY_VAN',
    description: 'Standard enclosed 53-foot trailer. Most common trailer in the US for general freight.',
    deckHeight: 4.0,
    deckLength: 53,
    deckWidth: 8.5,
    maxCargoWeight: 45000,
    tareWeight: 15000,
    maxLegalCargoHeight: 9.5, // 13.5 - 4.0 (interior ceiling ~110" may be lower)
    maxLegalCargoWidth: 8.0, // Interior width slightly less
    features: [
      'Fully enclosed',
      'Weather protection',
      'Secure from theft',
      'Rear door loading',
      'Air ride suspension',
    ],
    bestFor: [
      'General freight',
      'Palletized goods',
      'Consumer products',
      'Retail merchandise',
      'Non-temperature sensitive goods',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },
  {
    id: 'reefer-53',
    name: "Reefer 53' (Refrigerated)",
    category: 'REEFER',
    description: 'Temperature-controlled 53-foot trailer. Maintains cargo at specified temperature.',
    deckHeight: 4.0,
    deckLength: 53,
    deckWidth: 8.5,
    maxCargoWeight: 43000,
    tareWeight: 17000,
    maxLegalCargoHeight: 8.5, // Slightly less due to refrigeration unit
    maxLegalCargoWidth: 8.0,
    features: [
      'Temperature controlled',
      'Multi-temp capability',
      'GPS temperature monitoring',
      'Insulated walls',
      'Continuous cooling',
    ],
    bestFor: [
      'Frozen foods',
      'Fresh produce',
      'Pharmaceuticals',
      'Temperature-sensitive chemicals',
      'Dairy products',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },
  {
    id: 'curtain-side',
    name: 'Curtain Side (Side Kit)',
    category: 'CURTAIN_SIDE',
    description: 'Flatbed with curtain side walls. Easy side access with weather protection.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 44000,
    tareWeight: 16000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Side curtain walls',
      'Easy side access',
      'Weather protection',
      'Quick loading/unloading',
      'Forklift accessible from sides',
    ],
    bestFor: [
      'Beverages',
      'Building materials',
      'Packaged goods',
      'Quick-turn freight',
      'Multi-stop deliveries',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },

  // ===========================
  // HEAVY HAUL / SUPERLOAD
  // ===========================
  {
    id: 'multi-axle-13',
    name: 'Multi-Axle 13-Line',
    category: 'MULTI_AXLE',
    description: '13-axle trailer for superloads. Used for the heaviest industrial equipment and transformers.',
    deckHeight: 2.5,
    deckLength: 60,
    deckWidth: 12.0, // Often wider for superloads
    wellLength: 45,
    wellHeight: 2.5,
    maxCargoWeight: 200000,
    tareWeight: 60000,
    maxLegalCargoHeight: 11.0,
    maxLegalCargoWidth: 12.0,
    features: [
      '13 axle lines',
      'Extreme weight capacity',
      'Hydraulic steering',
      'Height adjustable',
      'Police escort required',
    ],
    bestFor: [
      'Large power transformers',
      'Reactor vessels',
      'Turbines',
      'Heavy industrial equipment',
      'Bridge sections',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'multi-axle-19',
    name: 'Multi-Axle 19-Line',
    category: 'MULTI_AXLE',
    description: '19-axle trailer for the heaviest superloads. Maximum weight distribution for extreme loads.',
    deckHeight: 2.5,
    deckLength: 80,
    deckWidth: 14.0,
    wellLength: 60,
    wellHeight: 2.5,
    maxCargoWeight: 350000,
    tareWeight: 90000,
    maxLegalCargoHeight: 11.0,
    maxLegalCargoWidth: 14.0,
    features: [
      '19 axle lines',
      'Maximum weight capacity',
      'Computer-controlled steering',
      'Self-propelled option',
      'Multiple escort vehicles required',
    ],
    bestFor: [
      'Nuclear reactor components',
      'Largest transformers',
      'Refinery equipment',
      'Offshore platform modules',
      'Ship components',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'schnabel',
    name: 'Schnabel Trailer',
    category: 'SCHNABEL',
    description: 'Specialized trailer where cargo becomes part of the trailer structure. For the heaviest single-piece loads.',
    deckHeight: 3.0, // Variable based on configuration
    deckLength: 100, // Variable
    deckWidth: 16.0,
    wellLength: 60,
    wellHeight: 3.0,
    maxCargoWeight: 500000,
    tareWeight: 100000,
    maxLegalCargoHeight: 10.5,
    maxLegalCargoWidth: 16.0,
    features: [
      'Cargo is part of trailer',
      'Extreme weight capacity',
      'Modular configuration',
      'Self-propelled modules',
      'Maximum flexibility',
    ],
    bestFor: [
      'Largest transformers',
      'Pressure vessels',
      'Nuclear components',
      'Heavy refinery equipment',
      'Single-piece extreme loads',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'perimeter-beam',
    name: 'Perimeter / Beam Trailer',
    category: 'PERIMETER',
    description: 'Open frame trailer with no deck. Cargo sits between frame beams for maximum clearance.',
    deckHeight: 1.0, // Cargo hangs between beams
    deckLength: 48,
    deckWidth: 10.0,
    wellLength: 35,
    wellHeight: 1.0,
    maxCargoWeight: 60000,
    tareWeight: 25000,
    maxLegalCargoHeight: 12.5, // Maximum clearance
    maxLegalCargoWidth: 10.0,
    features: [
      'No solid deck',
      'Maximum height clearance',
      'Cargo between beams',
      'For extremely tall loads',
      'Adjustable beam width',
    ],
    bestFor: [
      'Extremely tall equipment',
      'Tall tanks and vessels',
      'Oversized generators',
      'Maximum height loads',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'steerable-dolly',
    name: 'Steerable Dolly Trailer',
    category: 'STEERABLE',
    description: 'Trailer with steerable rear axles for tight turns. Essential for long loads in urban areas.',
    deckHeight: 2.0,
    deckLength: 53,
    deckWidth: 8.5,
    wellLength: 40,
    wellHeight: 2.0,
    maxCargoWeight: 48000,
    tareWeight: 22000,
    maxLegalCargoHeight: 11.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Rear axle steering',
      'Better maneuverability',
      'Tighter turning radius',
      'Rear steer operator',
      'For congested areas',
    ],
    bestFor: [
      'Long loads in cities',
      'Tight delivery locations',
      'Wind turbine components',
      'Construction in urban areas',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'blade-trailer',
    name: 'Blade Trailer (Wind Turbine)',
    category: 'BLADE',
    description: "Specialized trailer for wind turbine blades. Adaptable for blades 150'+.",
    deckHeight: 4.0,
    deckLength: 180, // Can handle very long blades
    deckWidth: 8.5,
    maxCargoWeight: 30000,
    tareWeight: 25000,
    maxLegalCargoHeight: 9.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Blade-specific cradle',
      'Pivoting support',
      'Self-steering rear',
      "For blades 150'+",
      'GPS tracking for route',
    ],
    bestFor: [
      'Wind turbine blades',
      'Long composite structures',
      'Aerospace components',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },

  // ===========================
  // ADDITIONAL FLATBED VARIANTS
  // ===========================
  {
    id: 'flatbed-moffett',
    name: 'Flatbed with Moffett',
    category: 'FLATBED',
    description: 'Standard flatbed with mounted Moffett forklift for self-unloading at delivery sites without dock access.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 42000, // Reduced due to forklift weight
    tareWeight: 21000, // Includes Moffett weight (~6000 lbs)
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Mounted Moffett forklift',
      'Self-unloading capability',
      'No dock required at delivery',
      'Forklift capacity 5,000-8,000 lbs',
    ],
    bestFor: [
      'Building materials to job sites',
      'Deliveries without forklift access',
      'Roofing materials',
      'Lumber yards',
      'Multi-stop deliveries',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },
  {
    id: 'flatbed-piggyback',
    name: 'Flatbed with Piggyback',
    category: 'FLATBED',
    description: 'Flatbed with attachable/detachable forklift. More flexible than Moffett.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 44000,
    tareWeight: 19000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Detachable piggyback forklift',
      'More cargo capacity when forklift not needed',
      'Versatile delivery options',
      'Can be left at job site',
    ],
    bestFor: [
      'Flexible delivery requirements',
      'When forklift may or may not be needed',
      'Construction sites',
      'Agricultural deliveries',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },
  {
    id: 'aluminum-flatbed',
    name: 'Aluminum Flatbed',
    category: 'FLATBED',
    description: 'Lightweight aluminum construction for maximum payload capacity.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 52000, // Higher due to lighter tare
    tareWeight: 11000, // ~4000 lbs lighter than steel
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Lightweight aluminum construction',
      'Maximum payload capacity',
      'Corrosion resistant',
      'Better fuel economy',
    ],
    bestFor: [
      'Maximum weight loads',
      'Heavy commodities',
      'Steel coils (maximizing payload)',
      'When every pound counts',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'combo-flatbed',
    name: 'Combo Flatbed/Step Deck',
    category: 'FLATBED',
    description: 'Convertible trailer that works as flatbed or step deck. Flip-down front section.',
    deckHeight: 5.0, // As flatbed
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 37, // When converted to step deck
    maxCargoWeight: 45000,
    tareWeight: 17000,
    maxLegalCargoHeight: 8.5, // As flatbed; 10.0 as step deck
    maxLegalCargoWidth: 8.5,
    features: [
      'Converts from flatbed to step deck',
      'Flip-down front section',
      'Maximum versatility',
      'Two trailers in one',
    ],
    bestFor: [
      'Mixed cargo requirements',
      'Varying height loads',
      'Maximum fleet flexibility',
      'Owner-operators',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },

  // ===========================
  // ADDITIONAL STEP DECK VARIANTS
  // ===========================
  {
    id: 'step-deck-ramps',
    name: 'Step Deck with Ramps',
    category: 'STEP_DECK',
    description: 'Step deck with heavy-duty built-in ramps for drive-on loading.',
    deckHeight: 3.5,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 37,
    deckZones: [
      { name: 'upper', startX: 0, endX: 11, deckHeight: 5.0, maxCargoHeight: 8.5 },
      { name: 'lower', startX: 11, endX: 48, deckHeight: 3.5, maxCargoHeight: 10.0 },
    ],
    maxCargoWeight: 46000,
    tareWeight: 18000,
    maxLegalCargoHeight: 10.0, // 13.5 - 3.5 (lower deck)
    maxLegalCargoWidth: 8.5,
    features: [
      'Heavy-duty built-in ramps',
      'Drive-on loading standard',
      'Ramps rated for 30,000+ lbs',
      'Spring-assist ramp lift',
    ],
    bestFor: [
      'Self-propelled equipment',
      'Forklifts and telehandlers',
      'Agricultural equipment',
      'Rolling stock',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'drop-deck-combo',
    name: 'Drop Deck Combo',
    category: 'STEP_DECK',
    description: 'Adjustable deck height step deck with removable upper deck section.',
    deckHeight: 3.0, // Adjustable 3.0-3.5
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 40,
    maxCargoWeight: 44000,
    tareWeight: 18000,
    maxLegalCargoHeight: 10.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Removable upper deck section',
      'Adjustable deck height',
      'Extended well length when converted',
      'Multiple configuration options',
    ],
    bestFor: [
      'Variable height cargo',
      'Maximizing well length',
      'Mixed loads',
      'Versatile operations',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },

  // ===========================
  // ADDITIONAL RGN VARIANTS
  // ===========================
  {
    id: 'mini-rgn',
    name: 'Mini RGN',
    category: 'RGN',
    description: 'Compact removable gooseneck for smaller equipment. Perfect for skid steers and mini excavators.',
    deckHeight: 1.5,
    deckLength: 35,
    deckWidth: 8.5,
    wellLength: 20,
    wellHeight: 1.5,
    maxCargoWeight: 25000,
    tareWeight: 12000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Compact size',
      'Very low deck height',
      'Detachable gooseneck',
      'Perfect for compact equipment',
    ],
    bestFor: [
      'Compact excavators',
      'Skid steers',
      'Mini loaders',
      'Small tracked equipment',
      'Compact track loaders (CTL)',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },

  // ===========================
  // ADDITIONAL LOWBOY VARIANTS
  // ===========================
  {
    id: 'hydraulic-lowboy',
    name: 'Hydraulic Lowboy',
    category: 'LOWBOY',
    description: 'Lowboy with hydraulic deck raise/lower for flexible loading and dock access.',
    deckHeight: 1.5, // Can raise to 3.0
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 28,
    wellHeight: 1.5,
    maxCargoWeight: 48000,
    tareWeight: 26000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Hydraulic deck raise/lower',
      'Can adjust from 1.5\' to 3.0\'',
      'Dock loading capability',
      'Maximum flexibility',
    ],
    bestFor: [
      'Variable height requirements',
      'Dock loading situations',
      'When height adjustment needed',
      'Multi-purpose operations',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },

  // ===========================
  // ADDITIONAL DOUBLE DROP VARIANTS
  // ===========================
  {
    id: 'double-drop-beavertail',
    name: 'Double Drop with Beavertail',
    category: 'DOUBLE_DROP',
    description: 'Double drop with beavertail ramp for drive-on loading of self-propelled equipment.',
    deckHeight: 2.0,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 25,
    wellHeight: 2.0,
    deckZones: [
      { name: 'front', startX: 0, endX: 11.5, deckHeight: 4.5, maxCargoHeight: 9.0 },
      { name: 'well', startX: 11.5, endX: 36.5, deckHeight: 2.0, maxCargoHeight: 11.5 },
      { name: 'rear', startX: 36.5, endX: 48, deckHeight: 4.5, maxCargoHeight: 9.0 },
    ],
    maxCargoWeight: 43000,
    tareWeight: 19000,
    maxLegalCargoHeight: 11.5, // 13.5 - 2.0 (well)
    maxLegalCargoWidth: 8.5,
    features: [
      'Beavertail rear ramp',
      'Drive-on loading',
      'Low center well',
      'Self-propelled equipment capable',
    ],
    bestFor: [
      'Self-propelled equipment',
      'Rolling stock',
      'Tall wheeled machinery',
      'When crane not available',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },

  // ===========================
  // ADDITIONAL MULTI-AXLE HEAVY HAUL
  // ===========================
  {
    id: 'multi-axle-9',
    name: 'Multi-Axle 9-Line',
    category: 'MULTI_AXLE',
    description: '9-axle heavy haul trailer for superloads. Bridge between standard and extreme heavy haul.',
    deckHeight: 2.5,
    deckLength: 50,
    deckWidth: 10.0,
    wellLength: 35,
    wellHeight: 2.5,
    maxCargoWeight: 120000,
    tareWeight: 45000,
    maxLegalCargoHeight: 11.0,
    maxLegalCargoWidth: 10.0,
    features: [
      '9 axle lines',
      'Heavy haul capacity',
      'Hydraulic steering',
      'Police escort typically required',
    ],
    bestFor: [
      'Heavy industrial equipment',
      'Medium transformers',
      'Large machinery',
      'Mining equipment',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },

  // ===========================
  // SPECIALIZED TRAILERS (NEW)
  // ===========================
  {
    id: 'tower-trailer',
    name: 'Tower Section Trailer',
    category: 'SPECIALIZED',
    description: 'Specialized trailer for wind turbine tower sections and large cylindrical loads.',
    deckHeight: 3.0,
    deckLength: 60,
    deckWidth: 12.0,
    maxCargoWeight: 80000,
    tareWeight: 30000,
    maxLegalCargoHeight: 10.5,
    maxLegalCargoWidth: 12.0,
    features: [
      'Tower section cradles',
      'Wide deck for cylindrical loads',
      'Heavy-duty tie-downs',
      'Oversize permits typically required',
    ],
    bestFor: [
      'Wind turbine tower sections',
      'Large pipe',
      'Cylindrical tanks',
      'Large diameter loads',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'nacelle-trailer',
    name: 'Nacelle Trailer',
    category: 'SPECIALIZED',
    description: 'Purpose-built trailer for wind turbine nacelles and generator housings.',
    deckHeight: 3.5,
    deckLength: 45,
    deckWidth: 12.0,
    maxCargoWeight: 100000,
    tareWeight: 35000,
    maxLegalCargoHeight: 10.0,
    maxLegalCargoWidth: 12.0,
    features: [
      'Nacelle-specific mounting',
      'Extra-wide deck',
      'Heavy-duty capacity',
      'Specialized securing points',
    ],
    bestFor: [
      'Wind turbine nacelles',
      'Generator housings',
      'Large rectangular loads',
      'Heavy equipment housings',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },

  // ===========================
  // ADDITIONAL DRY VAN/REEFER
  // ===========================
  {
    id: 'dry-van-48',
    name: "Dry Van 48'",
    category: 'DRY_VAN',
    description: 'Standard enclosed 48-foot trailer. Common for general freight.',
    deckHeight: 4.0,
    deckLength: 48,
    deckWidth: 8.0, // Interior width
    maxCargoWeight: 44000,
    tareWeight: 14000,
    maxLegalCargoHeight: 9.5, // 13.5 - 4.0 (interior ceiling ~108" may be lower)
    maxLegalCargoWidth: 8.0,
    features: [
      'Fully enclosed',
      'Weather protection',
      'Secure from theft',
      'Rear door loading',
    ],
    bestFor: [
      'General freight',
      'Palletized goods',
      'Consumer products',
      'Retail merchandise',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },
  {
    id: 'reefer-48',
    name: "Reefer 48' (Refrigerated)",
    category: 'REEFER',
    description: 'Temperature-controlled 48-foot trailer for perishable goods.',
    deckHeight: 4.0,
    deckLength: 48,
    deckWidth: 8.0,
    maxCargoWeight: 42000,
    tareWeight: 16000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.0,
    features: [
      'Temperature controlled',
      'Multi-temp capability',
      'GPS temperature monitoring',
      'Insulated walls',
    ],
    bestFor: [
      'Frozen foods',
      'Fresh produce',
      'Pharmaceuticals',
      'Temperature-sensitive chemicals',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'forklift',
  },

  // ===========================
  // ADDITIONAL LANDOLL
  // ===========================
  {
    id: 'landoll-50',
    name: "Landoll 50' (Extended)",
    category: 'LANDOLL',
    description: "Extended 50-foot Landoll tilt bed for longer cargo that doesn't require crane loading.",
    deckHeight: 2.5,
    deckLength: 50,
    deckWidth: 8.5,
    maxCargoWeight: 48000,
    tareWeight: 20000,
    maxLegalCargoHeight: 11.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Extended 50\' deck',
      'Self-loading capability',
      'Tilts to ground level',
      'No external equipment needed',
    ],
    bestFor: [
      'Long containers',
      'Extended equipment',
      'Remote locations',
      'Long loads without crane',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'tilt',
  },

  // ===========================
  // TANKER TRAILERS (NEW CATEGORY)
  // ===========================
  {
    id: 'tanker-liquid',
    name: 'Liquid Tanker',
    category: 'TANKER',
    description: 'Standard tanker for liquid commodities including fuel, chemicals, and food-grade liquids.',
    deckHeight: 8.0, // Cylindrical height
    deckLength: 42,
    deckWidth: 8.0,
    maxCargoWeight: 50000,
    tareWeight: 12000,
    maxLegalCargoHeight: 5.5, // Ground clearance effective
    maxLegalCargoWidth: 8.0,
    features: [
      'Liquid cargo transport',
      'Multiple compartments available',
      'Food-grade options',
      'Hazmat certified options',
    ],
    bestFor: [
      'Fuel transport',
      'Chemicals',
      'Food-grade liquids',
      'Industrial liquids',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'pump',
  },
  {
    id: 'pneumatic-tanker',
    name: 'Pneumatic Tanker',
    category: 'TANKER',
    description: 'Pressurized tanker for dry bulk commodities that discharge via air pressure.',
    deckHeight: 10.0,
    deckLength: 42,
    deckWidth: 8.0,
    maxCargoWeight: 48000,
    tareWeight: 14000,
    maxLegalCargoHeight: 3.5,
    maxLegalCargoWidth: 8.0,
    features: [
      'Pneumatic discharge',
      'Sealed transport',
      'Food-grade options',
      'Rapid unloading',
    ],
    bestFor: [
      'Cement',
      'Flour',
      'Plastic pellets',
      'Dry bulk commodities',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'pneumatic',
  },

  // ===========================
  // HOPPER TRAILERS (NEW CATEGORY)
  // ===========================
  {
    id: 'hopper-bottom',
    name: 'Hopper Bottom',
    category: 'HOPPER',
    description: 'Gravity-discharge trailer for agricultural products and bulk materials.',
    deckHeight: 10.0,
    deckLength: 42,
    deckWidth: 8.0,
    maxCargoWeight: 55000,
    tareWeight: 13000,
    maxLegalCargoHeight: 3.5,
    maxLegalCargoWidth: 8.0,
    features: [
      'Gravity discharge',
      'Double or triple hopper',
      'Easy unloading',
      'Agricultural standard',
    ],
    bestFor: [
      'Grain',
      'Sand',
      'Gravel',
      'Agricultural products',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'gravity',
  },
  {
    id: 'end-dump',
    name: 'End Dump Trailer',
    category: 'HOPPER',
    description: 'Hydraulic dump trailer for bulk materials and construction debris.',
    deckHeight: 6.0,
    deckLength: 38,
    deckWidth: 8.0,
    maxCargoWeight: 50000,
    tareWeight: 15000,
    maxLegalCargoHeight: 7.5,
    maxLegalCargoWidth: 8.0,
    features: [
      'Hydraulic dump',
      'Rapid unloading',
      'Heavy-duty construction',
      'High sides available',
    ],
    bestFor: [
      'Construction debris',
      'Aggregates',
      'Scrap metal',
      'Demolition materials',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'dump',
  },
  {
    id: 'side-dump',
    name: 'Side Dump Trailer',
    category: 'HOPPER',
    description: 'Hydraulic side-dumping trailer for materials requiring lateral discharge.',
    deckHeight: 5.5,
    deckLength: 40,
    deckWidth: 8.5,
    maxCargoWeight: 52000,
    tareWeight: 14000,
    maxLegalCargoHeight: 8.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Side-dumping capability',
      'Faster unloading than end dump',
      'Can dump while moving',
      'Better stability than end dump',
    ],
    bestFor: [
      'Road construction',
      'Mining operations',
      'Aggregates',
      'Large stockpile building',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'dump',
  },

  // ===========================
  // ADDITIONAL SPECIALIZED TRAILERS (EXPANDED)
  // ===========================
  {
    id: 'spmt',
    name: 'SPMT (Self-Propelled Modular Transporter)',
    category: 'SPECIALIZED',
    description: 'Self-propelled modular platform trailers for the largest and heaviest loads. Can be combined for extreme capacity.',
    deckHeight: 1.5,
    deckLength: 100,
    deckWidth: 20.0,
    wellLength: 100,
    wellHeight: 1.5,
    maxCargoWeight: 800000,
    tareWeight: 150000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 20.0,
    features: [
      'Self-propelled - no tractor required',
      'Modular - add units for more capacity',
      'All-wheel steering',
      'Computer-controlled positioning',
      'Hydraulic height adjustment',
      'Can move in any direction',
    ],
    bestFor: [
      'Refinery modules',
      'Bridge sections',
      'Building relocations',
      'Ship components',
      'Offshore platform modules',
      'Nuclear components',
    ],
    powerUnitWeight: 0,
    loadingMethod: 'crane',
  },
  {
    id: 'extendable-rgn-80',
    name: "Extendable RGN 80'",
    category: 'RGN',
    description: "Heavy-duty extendable RGN that can stretch to 80 feet for very long equipment.",
    deckHeight: 2.0,
    deckLength: 80,
    deckWidth: 8.5,
    wellLength: 60,
    wellHeight: 2.0,
    maxCargoWeight: 45000,
    tareWeight: 26000,
    maxLegalCargoHeight: 11.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Extends from 48\' to 80\'',
      'Detachable gooseneck',
      'Multiple axle configurations',
      'For very long equipment',
    ],
    bestFor: [
      'Long-reach excavators',
      'Extended cranes',
      'Drilling equipment',
      'Long industrial machinery',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'double-wide-flatbed',
    name: 'Double-Wide Flatbed',
    category: 'SPECIALIZED',
    description: 'Extra-wide flatbed for oversize loads that exceed standard width limits. Requires permits.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 12.0,
    maxCargoWeight: 44000,
    tareWeight: 18000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 12.0,
    features: [
      'Extra-wide deck (12\')',
      'For width-oversize loads',
      'Pilot/escort cars required',
      'State permits required',
    ],
    bestFor: [
      'Wide industrial equipment',
      'Pre-fabricated building sections',
      'Wide agricultural equipment',
      'Manufacturing equipment',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'jeep-dolly',
    name: 'Jeep and Dolly Combination',
    category: 'MULTI_AXLE',
    description: 'Jeep (front) and dolly (rear) axle set to extend weight capacity of standard trailers.',
    deckHeight: 2.0,
    deckLength: 48,
    deckWidth: 8.5,
    wellLength: 29,
    wellHeight: 2.0,
    maxCargoWeight: 80000,
    tareWeight: 35000,
    maxLegalCargoHeight: 11.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Adds axles to standard trailer',
      'Jeep adds 2 axles in front',
      'Dolly adds 2-3 axles in rear',
      'Increases weight capacity',
    ],
    bestFor: [
      'Heavy equipment exceeding standard limits',
      'Large excavators',
      'Heavy mining equipment',
      'Transformers on standard trailers',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'auto-carrier-8',
    name: 'Auto Carrier 8-Car',
    category: 'SPECIALIZED',
    description: 'Standard auto transport carrier for 8-10 vehicles. Hydraulic ramps for loading.',
    deckHeight: 3.5,
    deckLength: 75,
    deckWidth: 8.5,
    maxCargoWeight: 48000,
    tareWeight: 22000,
    maxLegalCargoHeight: 10.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Multi-level vehicle transport',
      'Hydraulic ramps',
      'Adjustable deck positions',
      'Fits 8-10 standard cars',
    ],
    bestFor: [
      'Car dealership deliveries',
      'Auction transport',
      'Fleet vehicles',
      'Consumer vehicle transport',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'auto-carrier-wedge',
    name: 'Wedge Auto Carrier',
    category: 'SPECIALIZED',
    description: 'Wedge-style enclosed auto carrier for high-value vehicles.',
    deckHeight: 3.0,
    deckLength: 53,
    deckWidth: 8.5,
    maxCargoWeight: 25000,
    tareWeight: 18000,
    maxLegalCargoHeight: 10.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Enclosed protection',
      'Climate controlled options',
      'Fits 4-6 vehicles',
      'Hydraulic lift gate',
    ],
    bestFor: [
      'Exotic cars',
      'Classic vehicles',
      'High-value automobiles',
      'Auction-quality transport',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'heavy-equipment-float',
    name: 'Heavy Equipment Float',
    category: 'SPECIALIZED',
    description: 'Reinforced flatbed designed for very heavy concentrated loads. Extra reinforced deck.',
    deckHeight: 4.5,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 60000,
    tareWeight: 20000,
    maxLegalCargoHeight: 9.0,
    maxLegalCargoWidth: 8.5,
    features: [
      'Reinforced deck structure',
      'Higher concentrated load capacity',
      'Heavy-duty tie-downs',
      'Designed for equipment with tracks',
    ],
    bestFor: [
      'Tracked excavators',
      'Bulldozers',
      'Heavy industrial equipment',
      'Concentrated heavy loads',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
  {
    id: 'expandable-flatbed',
    name: 'Expandable Width Flatbed',
    category: 'SPECIALIZED',
    description: 'Flatbed with expandable width capability for extra-wide loads.',
    deckHeight: 5.0,
    deckLength: 48,
    deckWidth: 10.0, // Expanded width
    maxCargoWeight: 42000,
    tareWeight: 19000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 10.0,
    features: [
      'Width expands from 8.5\' to 10\'',
      'Hydraulic expansion',
      'For moderately wide loads',
      'More economical than double-wide',
    ],
    bestFor: [
      'Wide but not extreme loads',
      'Farm equipment',
      'Industrial tanks',
      'Pre-cast concrete sections',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'oil-field-lowboy',
    name: 'Oil Field Lowboy',
    category: 'LOWBOY',
    description: 'Heavy-duty lowboy designed for oil field equipment with extra reinforcement.',
    deckHeight: 1.5,
    deckLength: 50,
    deckWidth: 10.0,
    wellLength: 30,
    wellHeight: 1.5,
    maxCargoWeight: 75000,
    tareWeight: 32000,
    maxLegalCargoHeight: 12.0,
    maxLegalCargoWidth: 10.0,
    features: [
      'Extra-wide deck (10\')',
      'Heavy-duty construction',
      'Designed for drilling equipment',
      'Reinforced for concentrated loads',
    ],
    bestFor: [
      'Drilling rigs',
      'Oil field compressors',
      'Frac equipment',
      'Pipeline equipment',
    ],
    powerUnitWeight: 20000,
    loadingMethod: 'crane',
  },
  {
    id: 'beam-hauler',
    name: 'Beam Hauler Trailer',
    category: 'SPECIALIZED',
    description: 'Specialized trailer for very long structural beams and bridge girders.',
    deckHeight: 5.0,
    deckLength: 120,
    deckWidth: 8.5,
    maxCargoWeight: 50000,
    tareWeight: 30000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Steerable rear axle',
      'Designed for long beams',
      'Support bolsters included',
      'Up to 120\' cargo',
    ],
    bestFor: [
      'Bridge girders',
      'Structural steel beams',
      'Long pipe strings',
      'Utility poles',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'pole-trailer',
    name: 'Pole Trailer (Logging)',
    category: 'SPECIALIZED',
    description: 'Traditional pole trailer for logs and long timber products.',
    deckHeight: 4.0,
    deckLength: 65,
    deckWidth: 8.5,
    maxCargoWeight: 55000,
    tareWeight: 18000,
    maxLegalCargoHeight: 9.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Pole connection between tractor and trailer',
      'Adjustable length',
      'Stakes for log containment',
      'Self-loading options available',
    ],
    bestFor: [
      'Sawlogs',
      'Timber products',
      'Utility poles',
      'Long pipe',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'crane',
  },
  {
    id: 'livestock-trailer',
    name: 'Livestock Trailer',
    category: 'SPECIALIZED',
    description: 'Ventilated trailer for safe transport of cattle, hogs, and other livestock.',
    deckHeight: 8.0,
    deckLength: 53,
    deckWidth: 8.5,
    maxCargoWeight: 48000,
    tareWeight: 18000,
    maxLegalCargoHeight: 5.5,
    maxLegalCargoWidth: 8.5,
    features: [
      'Ventilated sides',
      'Multiple deck levels',
      'Non-slip flooring',
      'Loading ramps',
    ],
    bestFor: [
      'Cattle transport',
      'Hog hauling',
      'Livestock to market',
      'Agricultural animals',
    ],
    powerUnitWeight: 17000,
    loadingMethod: 'drive-on',
  },
]

/**
 * Get truck by ID
 */
export function getTruckById(id: string): TruckType | undefined {
  return trucks.find(truck => truck.id === id)
}

/**
 * Get trucks by category
 */
export function getTrucksByCategory(category: TruckType['category']): TruckType[] {
  return trucks.filter(truck => truck.category === category)
}

/**
 * Get all unique categories
 */
export function getCategories(): TruckType['category'][] {
  return [...new Set(trucks.map(truck => truck.category))]
}
