import type { TruckType } from './types'

export const trucks: TruckType[] = [
  {
    id: 'flatbed-48',
    name: "Flatbed 48'",
    category: 'FLATBED',
    description: 'Standard flatbed trailer for general freight.',
    deckHeight: 5,
    deckLength: 48,
    deckWidth: 8.5,
    maxCargoWeight: 48000,
    maxLegalCargoHeight: 8.5,
    maxLegalCargoWidth: 8.5,
    features: ['Open deck', 'Easy side loading'],
    bestFor: ['Pallets', 'Crates', 'General freight'],
    loadingMethod: 'forklift',
  },
  {
    id: 'step-deck-53',
    name: "Step Deck 53'",
    category: 'STEP_DECK',
    description: 'Lower deck height for taller cargo.',
    deckHeight: 3.5,
    deckLength: 53,
    deckWidth: 8.5,
    wellLength: 42,
    maxCargoWeight: 46000,
    maxLegalCargoHeight: 10,
    maxLegalCargoWidth: 8.5,
    features: ['Lower deck', 'Taller cargo'],
    bestFor: ['Equipment', 'Machinery'],
    loadingMethod: 'ramp',
  },
  {
    id: 'rgn-50',
    name: "RGN 50'",
    category: 'RGN',
    description: 'Removable gooseneck for drive-on loading.',
    deckHeight: 2.5,
    deckLength: 50,
    deckWidth: 8.5,
    wellLength: 29,
    maxCargoWeight: 70000,
    maxLegalCargoHeight: 11,
    maxLegalCargoWidth: 8.5,
    features: ['Drive-on', 'Detachable neck'],
    bestFor: ['Excavators', 'Dozers'],
    loadingMethod: 'drive-on',
  },
  {
    id: 'lowboy-40',
    name: "Lowboy 40'",
    category: 'LOWBOY',
    description: 'Ultra-low deck for tall/heavy loads.',
    deckHeight: 2,
    deckLength: 40,
    deckWidth: 8.5,
    wellLength: 24,
    maxCargoWeight: 80000,
    maxLegalCargoHeight: 11.5,
    maxLegalCargoWidth: 8.5,
    features: ['Very low deck'],
    bestFor: ['Heavy machinery'],
    loadingMethod: 'drive-on',
  },
]
