export type {
  TrailerCategory,
  TruckType,
  DeckZone,
  PermitType,
  PermitRequired,
  FitAnalysis,
  TruckRecommendation,
  ItemGeometry,
  OrientationMode,
  LoadItem,
  ParsedLoad,
  Location,
  LoadStatus,
  LoadType,
  Load,
  ItemPlacement,
  PlannedLoad,
  LoadPlan,
  CargoSpecs,
  RouteRecommendation,
  TruckRouteRecommendation,
  RouteAlternative,
  RoutePermitSummary,
  DetailedPermitRequirement,
  EscortCostBreakdown,
  ScoreBreakdown,
  FitOptimization,
} from '../../../../dev_docs/11-ai-dev/operations/tmp_ops_src/lib/load-planner/types';

export {
  LEGAL_LIMITS,
  SECUREMENT_WIDTH_ALLOWANCE,
  SUPERLOAD_THRESHOLDS,
  OVERSIZE_SPEEDS,
  ESCORT_REGIONAL_MULTIPLIERS,
  DEFAULT_FUEL_SURCHARGE_CONFIG,
  EIA_DIESEL_PRICES,
  getDieselPriceForDate,
  calculateFuelSurchargePercent,
  calculateFuelSurchargeAmount,
  calculateFuelSurchargeDetailed,
  getEscortRegionalMultiplier,
  getRouteAverageMultiplier,
  getRouteMaxMultiplier,
  getTransportWidth,
  PERMIT_DATA_STALENESS,
  checkPermitDataStaleness,
  DEFAULT_BRIDGE_ANALYSIS,
  shouldWarnBridgeAnalysis,
} from '../../../../dev_docs/11-ai-dev/operations/tmp_ops_src/lib/load-planner/types';
