'use client'

import { useState, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import {
  GitCompareArrows,
  Trophy,
  MapPin,
  Truck,
  FileWarning,
  Clock,
  Route,
  Plus,
  Loader2,
  Check,
  AlertTriangle,
  Shield,
  ChevronDown,
  ChevronUp,
} from 'lucide-react'
import { calculateMultipleRoutes } from '@/lib/load-planner/client-route-calculator'
import { calculateDetailedRoutePermits } from '@/lib/load-planner/permit-calculator'
import type {
  RouteAlternative,
  CargoSpecs,
  DetailedRoutePermitSummary,
  TruckType,
  LoadItem,
} from '@/lib/load-planner/types'
import { formatDuration, type RouteResult } from '@/lib/load-planner/route-calculator'
import { trucks as allTrucks } from '@/lib/load-planner/trucks'
import { formatCurrency } from '@/lib/utils'
import { SearchableSelect, type SearchableSelectOption } from '@/components/ui/searchable-select'

// A scenario = one route + one truck type + calculated permits
export interface ComparisonScenario {
  id: string
  routeAlternative: RouteAlternative
  truck: TruckType
  cargoSpecs: CargoSpecs
  permitSummary: DetailedRoutePermitSummary
  lineHaulEstimate: number // cents - rough $/mile estimate
  totalEstimate: number // cents - permits + escorts + line haul
  isAutoGenerated: boolean
}

interface RouteComparisonTabProps {
  pickupAddress: string
  dropoffAddress: string
  cargoItems: LoadItem[]
  currentTruck: TruckType | null
  routeResult: RouteResult | null
  onApplyScenario: (scenario: ComparisonScenario) => void
}

// Rough line haul rate per mile in cents (national average for flatbed)
const DEFAULT_RATE_PER_MILE_CENTS = 350 // $3.50/mile

function estimateLineHaul(distanceMiles: number, truck: TruckType): number {
  // Adjust rate based on truck category
  const categoryMultipliers: Record<string, number> = {
    FLATBED: 1.0,
    STEP_DECK: 1.1,
    RGN: 1.4,
    LOWBOY: 1.6,
    DOUBLE_DROP: 1.3,
    LANDOLL: 1.2,
    CONESTOGA: 1.15,
    DRY_VAN: 0.9,
    MULTI_AXLE: 2.5,
    SCHNABEL: 4.0,
    SPECIALIZED: 2.0,
  }
  const multiplier = categoryMultipliers[truck.category] || 1.0
  return Math.round(distanceMiles * DEFAULT_RATE_PER_MILE_CENTS * multiplier)
}

function ScenarioCard({
  scenario,
  isWinner,
  isSelected,
  onSelect,
  onRemove,
  index,
}: {
  scenario: ComparisonScenario
  isWinner: boolean
  isSelected: boolean
  onSelect: () => void
  onRemove?: () => void
  index: number
}) {
  const [expanded, setExpanded] = useState(false)
  const route = scenario.routeAlternative
  const permits = scenario.permitSummary

  return (
    <Card
      className={`relative transition-all cursor-pointer ${
        isSelected
          ? 'ring-2 ring-blue-500 border-blue-500'
          : 'hover:border-gray-300'
      } ${isWinner ? 'border-green-300 bg-green-50/50' : ''}`}
      onClick={onSelect}
    >
      {/* Winner badge */}
      {isWinner && (
        <div className="absolute -top-2 -right-2 z-10">
          <Badge className="bg-green-600 text-white gap-1">
            <Trophy className="w-3 h-3" />
            Best Value
          </Badge>
        </div>
      )}

      {/* Selection indicator */}
      {isSelected && (
        <div className="absolute top-2 left-2 z-10">
          <div className="w-6 h-6 rounded-full bg-blue-500 flex items-center justify-center">
            <Check className="w-4 h-4 text-white" />
          </div>
        </div>
      )}

      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded bg-blue-100 text-blue-600">
              <Route className="w-4 h-4" />
            </div>
            <div>
              <CardTitle className="text-sm">
                {scenario.isAutoGenerated ? `Option ${String.fromCharCode(65 + index)}` : `Custom ${index + 1}`}
              </CardTitle>
              <p className="text-xs text-muted-foreground">{route.name}</p>
            </div>
          </div>
          {onRemove && !scenario.isAutoGenerated && (
            <Button
              variant="ghost"
              size="sm"
              className="h-6 w-6 p-0 text-gray-400 hover:text-red-500"
              onClick={(e) => {
                e.stopPropagation()
                onRemove()
              }}
            >
              ×
            </Button>
          )}
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        {/* Key metrics grid */}
        <div className="grid grid-cols-2 gap-2 text-center">
          <div className="p-2 bg-white rounded border border-gray-100">
            <div className="text-sm font-bold text-gray-900">
              {route.totalDistanceMiles.toLocaleString()} mi
            </div>
            <div className="text-xs text-gray-500 flex items-center justify-center gap-1">
              <MapPin className="w-3 h-3" />
              Distance
            </div>
          </div>
          <div className="p-2 bg-white rounded border border-gray-100">
            <div className="text-sm font-bold text-gray-900">
              {formatDuration(route.totalDurationMinutes)}
            </div>
            <div className="text-xs text-gray-500 flex items-center justify-center gap-1">
              <Clock className="w-3 h-3" />
              Drive Time
            </div>
          </div>
        </div>

        {/* Truck */}
        <div className="flex items-center gap-2 text-sm">
          <Truck className="w-4 h-4 text-purple-600 flex-shrink-0" />
          <span className="truncate font-medium">{scenario.truck.name}</span>
        </div>

        {/* States */}
        <div className="flex flex-wrap gap-1">
          {route.statesTraversed.map((state) => (
            <Badge key={state} variant="outline" className="text-xs px-1.5 py-0">
              {state}
            </Badge>
          ))}
        </div>

        <Separator />

        {/* Cost breakdown */}
        <div className="space-y-1.5">
          <div className="flex justify-between text-xs text-gray-600">
            <span>Line Haul (est.)</span>
            <span>{formatCurrency(scenario.lineHaulEstimate)}</span>
          </div>
          <div className="flex justify-between text-xs text-gray-600">
            <span className="flex items-center gap-1">
              <FileWarning className="w-3 h-3" />
              Permits ({permits.statePermits.length} states)
            </span>
            <span>{formatCurrency(permits.totalPermitCost)}</span>
          </div>
          {permits.totalEscortCost > 0 && (
            <div className="flex justify-between text-xs text-gray-600">
              <span className="flex items-center gap-1">
                <Shield className="w-3 h-3" />
                Escorts
              </span>
              <span>{formatCurrency(permits.totalEscortCost)}</span>
            </div>
          )}
          <Separator />
          <div className="flex justify-between font-semibold text-sm">
            <span>Total Estimate</span>
            <span className={isWinner ? 'text-green-700' : ''}>
              {formatCurrency(scenario.totalEstimate)}
            </span>
          </div>
        </div>

        {/* Expandable permit details */}
        <button
          type="button"
          className="flex items-center gap-1 text-xs text-blue-600 hover:text-blue-800"
          onClick={(e) => {
            e.stopPropagation()
            setExpanded(!expanded)
          }}
        >
          {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
          {expanded ? 'Hide' : 'Show'} permit details
        </button>

        {expanded && (
          <div className="space-y-1.5 text-xs bg-gray-50 rounded p-2">
            {permits.statePermits.length === 0 ? (
              <div className="flex items-center gap-1 text-green-600">
                <Shield className="w-3 h-3" />
                No permits required - 100% legal load
              </div>
            ) : (
              permits.statePermits.map((sp) => (
                <div key={sp.stateCode} className="flex justify-between">
                  <span className="font-medium">{sp.state}</span>
                  <span>
                    {sp.reasons.slice(0, 2).join(', ')} — {formatCurrency(sp.estimatedFee)}
                  </span>
                </div>
              ))
            )}
          </div>
        )}

        {/* Warnings */}
        {permits.warnings.length > 0 && (
          <div className="space-y-1">
            {permits.warnings.slice(0, 2).map((w, i) => (
              <div key={i} className="flex items-start gap-1 text-xs text-amber-600">
                <AlertTriangle className="w-3 h-3 mt-0.5 flex-shrink-0" />
                <span>{w}</span>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export function RouteComparisonTab({
  pickupAddress,
  dropoffAddress,
  cargoItems,
  currentTruck,
  routeResult,
  onApplyScenario,
}: RouteComparisonTabProps) {
  const [scenarios, setScenarios] = useState<ComparisonScenario[]>([])
  const [selectedScenarioId, setSelectedScenarioId] = useState<string | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showAddManual, setShowAddManual] = useState(false)
  const [manualTruck, setManualTruck] = useState<TruckType | null>(null)
  const [routeAlternatives, setRouteAlternatives] = useState<RouteAlternative[]>([])

  // Build cargo specs from current items
  const getCargoSpecs = useCallback((): CargoSpecs | null => {
    const items = cargoItems.filter((i) => i.length > 0 && i.width > 0 && i.height > 0)
    if (items.length === 0) return null

    const maxWidth = Math.max(...items.map((i) => i.width))
    const maxHeight = Math.max(...items.map((i) => i.height))
    const maxLength = Math.max(...items.map((i) => i.length))
    const totalWeight = items.reduce((sum, i) => sum + (i.weight || 0) * i.quantity, 0)

    // Add truck tare weight for gross weight
    const truckTare = currentTruck?.tareWeight || 35000
    return {
      width: maxWidth,
      height: maxHeight + (currentTruck?.deckHeight || 5), // cargo height + deck height
      length: maxLength,
      grossWeight: totalWeight + truckTare,
    }
  }, [cargoItems, currentTruck])

  // Auto-generate scenarios from Google Maps alternatives
  const handleAutoGenerate = useCallback(async () => {
    if (!pickupAddress || !dropoffAddress) {
      setError('Please set pickup and dropoff addresses in the Route tab first.')
      return
    }

    const cargo = getCargoSpecs()
    if (!cargo) {
      setError('Please add cargo items with dimensions in the Cargo tab first.')
      return
    }

    setIsGenerating(true)
    setError(null)

    try {
      const result = await calculateMultipleRoutes(pickupAddress, dropoffAddress, cargo)
      setRouteAlternatives(result.routes)

      // For each route, create scenarios with the current truck + top alternative trucks
      const newScenarios: ComparisonScenario[] = []
      const trucksToTry = currentTruck
        ? [currentTruck, ...getAlternativeTrucks(currentTruck, cargo).slice(0, 1)]
        : [allTrucks[0]] // Default to first flatbed

      for (const route of result.routes) {
        for (const truck of trucksToTry) {
          // Recalculate cargo specs with this truck's deck height
          const adjustedCargo: CargoSpecs = {
            ...cargo,
            height: Math.max(...cargoItems.filter(i => i.height > 0).map(i => i.height)) + truck.deckHeight,
            grossWeight: cargoItems.reduce((sum, i) => sum + (i.weight || 0) * i.quantity, 0) + truck.tareWeight,
          }

          const permitSummary = calculateDetailedRoutePermits(
            route.statesTraversed,
            adjustedCargo,
            route.stateDistances
          )

          const lineHaul = estimateLineHaul(route.totalDistanceMiles, truck)
          const totalEstimate = lineHaul + permitSummary.totalCost

          newScenarios.push({
            id: `${route.id}-${truck.id}`,
            routeAlternative: route,
            truck,
            cargoSpecs: adjustedCargo,
            permitSummary,
            lineHaulEstimate: lineHaul,
            totalEstimate,
            isAutoGenerated: true,
          })
        }
      }

      // Sort by total estimate
      newScenarios.sort((a, b) => a.totalEstimate - b.totalEstimate)
      setScenarios(newScenarios)

      // Auto-select the cheapest
      if (newScenarios.length > 0) {
        setSelectedScenarioId(newScenarios[0].id)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to calculate routes')
    } finally {
      setIsGenerating(false)
    }
  }, [pickupAddress, dropoffAddress, cargoItems, currentTruck, getCargoSpecs])

  // Add a manual scenario with a specific truck on an existing route
  const handleAddManualScenario = useCallback(() => {
    if (!manualTruck) return
    const cargo = getCargoSpecs()
    if (!cargo) return

    // Use available route alternatives, or fall back to first one
    const routes = routeAlternatives.length > 0 ? routeAlternatives : []
    if (routes.length === 0) {
      setError('Generate route options first, then add custom truck scenarios.')
      return
    }

    const newScenarios: ComparisonScenario[] = [...scenarios]

    for (const route of routes) {
      const adjustedCargo: CargoSpecs = {
        ...cargo,
        height: Math.max(...cargoItems.filter(i => i.height > 0).map(i => i.height)) + manualTruck.deckHeight,
        grossWeight: cargoItems.reduce((sum, i) => sum + (i.weight || 0) * i.quantity, 0) + manualTruck.tareWeight,
      }

      const permitSummary = calculateDetailedRoutePermits(
        route.statesTraversed,
        adjustedCargo,
        route.stateDistances
      )

      const lineHaul = estimateLineHaul(route.totalDistanceMiles, manualTruck)
      const totalEstimate = lineHaul + permitSummary.totalCost

      const id = `manual-${route.id}-${manualTruck.id}`
      // Don't add duplicate
      if (newScenarios.some((s) => s.id === id)) continue

      newScenarios.push({
        id,
        routeAlternative: route,
        truck: manualTruck,
        cargoSpecs: adjustedCargo,
        permitSummary,
        lineHaulEstimate: lineHaul,
        totalEstimate,
        isAutoGenerated: false,
      })
    }

    newScenarios.sort((a, b) => a.totalEstimate - b.totalEstimate)
    setScenarios(newScenarios)
    setShowAddManual(false)
    setManualTruck(null)
  }, [manualTruck, routeAlternatives, scenarios, cargoItems, getCargoSpecs])

  const handleRemoveScenario = useCallback(
    (id: string) => {
      setScenarios((prev) => prev.filter((s) => s.id !== id))
      if (selectedScenarioId === id) {
        setSelectedScenarioId(null)
      }
    },
    [selectedScenarioId]
  )

  const selectedScenario = scenarios.find((s) => s.id === selectedScenarioId) || null
  const winnerId = scenarios.length > 0 ? scenarios[0].id : null // Already sorted by cost

  const canGenerate = pickupAddress && dropoffAddress && cargoItems.some((i) => i.length > 0)

  return (
    <div className="space-y-4">
      {/* Header */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GitCompareArrows className="h-5 w-5 text-blue-600" />
              <div>
                <CardTitle>Route & Truck Comparison</CardTitle>
                <p className="text-sm text-muted-foreground mt-1">
                  Compare different route paths, truck types, and permit costs to find the best combo
                </p>
              </div>
            </div>
            <div className="flex gap-2">
              <Button
                onClick={handleAutoGenerate}
                disabled={isGenerating || !canGenerate}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin mr-2" />
                    Analyzing Routes...
                  </>
                ) : (
                  <>
                    <Route className="w-4 h-4 mr-2" />
                    {scenarios.length > 0 ? 'Refresh' : 'Auto-Generate'}
                  </>
                )}
              </Button>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Error */}
      {error && (
        <div className="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
          <AlertTriangle className="w-4 h-4 flex-shrink-0" />
          {error}
        </div>
      )}

      {/* No scenarios yet */}
      {scenarios.length === 0 && !isGenerating && (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center justify-center py-12 text-center">
            <GitCompareArrows className="w-12 h-12 text-gray-300 mb-3" />
            <h3 className="font-medium text-gray-600 mb-1">No scenarios generated yet</h3>
            <p className="text-sm text-gray-500 max-w-md mb-4">
              Click &quot;Auto-Generate&quot; to calculate multiple route alternatives with different truck types and
              see which combination gives you the best price.
            </p>
            {!canGenerate && (
              <p className="text-xs text-amber-600">
                Fill in pickup/dropoff addresses and add cargo items first.
              </p>
            )}
          </CardContent>
        </Card>
      )}

      {/* Scenario cards */}
      {scenarios.length > 0 && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {scenarios.map((scenario, i) => (
              <ScenarioCard
                key={scenario.id}
                scenario={scenario}
                isWinner={scenario.id === winnerId}
                isSelected={scenario.id === selectedScenarioId}
                onSelect={() => setSelectedScenarioId(scenario.id)}
                onRemove={
                  !scenario.isAutoGenerated
                    ? () => handleRemoveScenario(scenario.id)
                    : undefined
                }
                index={i}
              />
            ))}
          </div>

          {/* Add custom truck scenario */}
          {routeAlternatives.length > 0 && (
            <div>
              {showAddManual ? (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-sm">Add Custom Truck Scenario</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <p className="text-sm text-muted-foreground">
                      Pick a truck type to see how it compares across all route alternatives.
                    </p>
                    <SearchableSelect
                      options={allTrucks.map((t): SearchableSelectOption => ({
                        value: t.id,
                        label: `${t.name} (${t.category})`,
                      }))}
                      value={manualTruck?.id || ''}
                      onChange={(val) => {
                        const truck = allTrucks.find((t) => t.id === val)
                        setManualTruck(truck || null)
                      }}
                      placeholder="Select a truck type..."
                    />
                    <div className="flex gap-2">
                      <Button
                        onClick={handleAddManualScenario}
                        disabled={!manualTruck}
                        size="sm"
                      >
                        Add Scenarios
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          setShowAddManual(false)
                          setManualTruck(null)
                        }}
                      >
                        Cancel
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Button
                  variant="outline"
                  className="w-full border-dashed"
                  onClick={() => setShowAddManual(true)}
                >
                  <Plus className="w-4 h-4 mr-2" />
                  Add Custom Truck Scenario
                </Button>
              )}
            </div>
          )}

          {/* Apply button */}
          {selectedScenario && (
            <Card className="bg-blue-50 border-blue-200">
              <CardContent className="flex items-center justify-between py-4">
                <div>
                  <p className="font-medium text-blue-900">
                    Selected: {selectedScenario.routeAlternative.name} + {selectedScenario.truck.name}
                  </p>
                  <p className="text-sm text-blue-700">
                    Est. total: {formatCurrency(selectedScenario.totalEstimate)} •{' '}
                    {selectedScenario.routeAlternative.totalDistanceMiles.toLocaleString()} mi •{' '}
                    {selectedScenario.permitSummary.statePermits.length} permit states
                  </p>
                </div>
                <Button
                  onClick={() => onApplyScenario(selectedScenario)}
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  <Check className="w-4 h-4 mr-2" />
                  Apply to Quote
                </Button>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  )
}

/**
 * Get a few alternative truck types that could work for this cargo
 */
function getAlternativeTrucks(currentTruck: TruckType, cargo: CargoSpecs): TruckType[] {
  // Find trucks that can physically fit the cargo and are a different category
  return allTrucks
    .filter(
      (t) =>
        t.id !== currentTruck.id &&
        t.category !== currentTruck.category &&
        t.deckLength >= cargo.length &&
        t.deckWidth >= cargo.width &&
        t.maxCargoWeight >= cargo.grossWeight - t.tareWeight
    )
    .slice(0, 3)
}
